name: Build and Test

on:
  push:
    branches:
      - main  # Run on main branch, you can adjust this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  # Change to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal --filter FullyQualifiedName=UnitTest.UnitTest1 --logger:"trx;LogFileName=test_results.trx"
        if [ $? -ne 0 ]; then
          echo "Tests failed, failing the build"
          exit 1
        fi

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results.trx
